kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: template-service-broker-ingress
spec:
  podSelector:
    matchLabels:
      apiserver: "true"
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-service-catalog
      ports:
        - port: 8443
          protocol: TCP
