---
- name: Define {{ machineset_group.name }} machinesets
  k8s:
    state: present
    definition: "{{ lookup('template', 'aws-machineset.yml.j2') | from_yaml }}"
  # Iterate through availability zones in reverse order as it makes the math
  # easier to scale zone "a" before "b" to match expected behavior.
  loop: "{{ availability_zones[::-1] }}"
  loop_control:
    label: "{{ machineset_name }}"
    loop_var: availability_zone
    index_var: loop_index
  vars:
    ami_id: >-
      {{ machineset_group.aws_ami_id
       | default(aws_coreos_ami_id_by_region[region])
      }}
    region: >-
      {{ availability_zone.name[:-1] }}
    subnet_search_key: >-
      {{ availability_zone.subnet_search_key
       | default('subnet-id')
      }}
    subnet_search_value: >-
      {{ availability_zone.subnet_search_value }}
    instance_type: >-
      {{ machineset_group.aws_instance_type | default(default_aws_instance_type) }}
    machineset_name: >-
      {{ [cluster_infra_id, machineset_group.name, availability_zone.name] | join('-') }}
    machineset_node_labels: >-
      {{ machineset_group.node_labels
       | default({'node-role.kubernetes.io/' + machineset_group.role: ''}
           if machineset_group.role|default(False) else {})
      }}
    machineset_group_total_replicas: >-
      {{ machineset_group.total_replicas
       | default(machineset_group.total_replicas_min)
       | default(0)
      }}
    machineset_replicas: >-
      {{ (
        (machineset_group_total_replicas|int + loop_index) / availability_zones|count
      ) | int }}
    root_volume_size: >-
      {{ machineset_group.aws_root_volume_size | default(default_aws_root_volume_size) }}

- name: Define {{ machineset_group.name }} machineautoscalers
  k8s:
    state: present
    definition: "{{ lookup('template', 'machineautoscaler.yml.j2') | from_yaml }}"
  # Iterate through availability zones in reverse order as it makes the math
  # easier to scale zone "a" before "b" to match expected behavior.
  loop: "{{ availability_zones[::-1] }}"
  loop_control:
    label: "{{ machineset_name }}"
    loop_var: availability_zone
    index_var: loop_index
  vars:
    machineset_name: >-
      {{ [cluster_infra_id, machineset_group.name, availability_zone.name] | join('-') }}
    machineset_min_replicas: >-
      {{ (
         (machineset_group.total_replicas_min|default(0) + loop_index) /
         availability_zones|count
      ) | int }}
    machineset_max_replicas: >-
      {{ (
         (machineset_group.total_replicas_max|default(100) + loop_index) /
         availability_zones|count
      ) | int }}
  when: machineset_group.autoscale | default(False) | bool
