---
- name: Set machineset facts
  include_tasks: set-facts.yml

- name: Configure machinesets for cloud provider
  include_tasks: "{{ openshift_machineset_config_cloud_provider }}.yml"

- name: Disable default worker machinesets
  include_tasks: disable-default-worker-machinesets.yml
  when: disable_default_worker_machinesets|bool

- name: Enable cluster autoscaler
  include_tasks: enable-cluster-autoscaler.yml
  when: >-
    openshift_machineset_config_groups | json_query('[?autoscale]')
