kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: cassandra-nodes-ingress
spec:
  podSelector:
    matchLabels:
      metrics-infra: hawkular-cassandra
  ingress:
    - from:
      - podSelector:
          matchLabels:
            metrics-infra: hawkular-cassandra
