kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: cassandra-hawkular-ingress
spec:
  podSelector:
    matchLabels:
      metrics-infra: hawkular-cassandra
  ingress:
    - from:
      - podSelector:
          matchLabels:
            metrics-infra: hawkular-metrics
      ports:
        - port: 9042
          protocol: TCP
