kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: registry-allow-other-namespaces
spec:
  podSelector:
    matchLabels:
      docker-registry: default
  ingress:
    - from:
      - namespaceSelector:
          matchLabels: {}
      ports:
        - port: 5000
          protocol: TCP
