kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: elasticsearch-nodes-ingress
spec:
  podSelector:
    matchLabels:
      component: es
  ingress:
    - from:
      - podSelector:
          matchLabels:
            component: es
