apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
  namespace: default
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${PROJECT_NAME}
  userNames: null
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:builder
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:deployer
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_ADMIN_USER}
  userNames:
  - ${PROJECT_ADMIN_USER}
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: Small
    labels:
      quota-tier: Small
    name: quota
    namespace: ${PROJECT_NAME}
   spec:
    hard:
      cpu: "1"
      memory: 6Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: Small
    labels:
      quota-tier: Small
    name: burst-quota
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      cpu: "2"
      memory: 8Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    annotations:
      openshift.io/quota-tier: Small
    labels:
      quota-tier: Small
    name: limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 10m
        memory: 128Mi
      type: Pod
    - default:
        cpu: 100m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 256Mi
      max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 10m
        memory: 128Mi
      type: Container
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
